// Basic IATA code -> city name mapping for common airports. Used as a fallback
// when inferring destinations from flight reservations.
const AIRPORT_CITY_MAP: Record<string, string> = {
  // United States
  ATL: 'Atlanta',
  AUS: 'Austin',
  BNA: 'Nashville',
  BOS: 'Boston',
  BWI: 'Baltimore',
  CLT: 'Charlotte',
  DCA: 'Washington, D.C.',
  DEN: 'Denver',
  DFW: 'Dallas-Fort Worth',
  DTW: 'Detroit',
  EWR: 'Newark',
  FLL: 'Fort Lauderdale',
  HNL: 'Honolulu',
  HOU: 'Houston',
  IAD: 'Washington, D.C.',
  IND: 'Indianapolis',
  JFK: 'New York',
  LAS: 'Las Vegas',
  LAX: 'Los Angeles',
  MCI: 'Kansas City',
  MCO: 'Orlando',
  MIA: 'Miami',
  MSP: 'Minneapolis',
  MSY: 'New Orleans',
  OAK: 'Oakland',
  ORD: 'Chicago',
  PDX: 'Portland',
  PHL: 'Philadelphia',
  PHX: 'Phoenix',
  RDU: 'Raleigh',
  SAN: 'San Diego',
  SEA: 'Seattle',
  SFO: 'San Francisco',
  SJC: 'San Jose',
  SLC: 'Salt Lake City',
  SMF: 'Sacramento',
  STL: 'St. Louis',
  TPA: 'Tampa',

  // Europe
  AMS: 'Amsterdam',
  ARN: 'Stockholm',
  ATH: 'Athens',
  BCN: 'Barcelona',
  BER: 'Berlin',
  BRU: 'Brussels',
  BUD: 'Budapest',
  CDG: 'Paris',
  CPH: 'Copenhagen',
  DUB: 'Dublin',
  DUS: 'Dusseldorf',
  FCO: 'Rome',
  FRA: 'Frankfurt',
  GVA: 'Geneva',
  HEL: 'Helsinki',
  IST: 'Istanbul',
  LHR: 'London',
  LIS: 'Lisbon',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MUC: 'Munich',
  MXP: 'Milan',
  NCE: 'Nice',
  OLB: 'Olbia',
  OSL: 'Oslo',
  PRG: 'Prague',
  VCE: 'Venice',
  VIE: 'Vienna',
  ZRH: 'Zurich',

  // Asia / Pacific
  BKK: 'Bangkok',
  CAN: 'Guangzhou',
  DEL: 'Delhi',
  DXB: 'Dubai',
  HKG: 'Hong Kong',
  HND: 'Tokyo',
  ICN: 'Seoul',
  KIX: 'Osaka',
  MEL: 'Melbourne',
  NRT: 'Tokyo',
  PEK: 'Beijing',
  SGN: 'Ho Chi Minh City',
  SIN: 'Singapore',
  SYD: 'Sydney',
  TPE: 'Taipei',

  // Americas / Caribbean
  BOG: 'Bogotá',
  CUN: 'Cancun',
  CTG: 'Cartagena',
  EZE: 'Buenos Aires',
  GIG: 'Rio de Janeiro',
  GRU: 'São Paulo',
  HAV: 'Havana',
  LIM: 'Lima',
  MEX: 'Mexico City',
  PUJ: 'Punta Cana',
  SCL: 'Santiago',
  SJD: 'Los Cabos',
  SJU: 'San Juan',
  YVR: 'Vancouver',
  YYZ: 'Toronto',
};

export function getCityForAirport(code: string): string | undefined {
  return AIRPORT_CITY_MAP[code.toUpperCase()];
}
